language: node_js
node_js:
  - "4"

sudo: required
dist: trusty

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run-script tsc

notifications:
  email: false
  slack: tud-contextproject-16:7oE95aUGOwGTYonAvcVxYcGr