language: node_js
node_js:
  - "4"

sudo: required
dist: trusty

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

# Commands that fail in before_script will error the build
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run-script tslint   # Check on style errors before transpiling
  - npm run-script tsc      # Transpile

# Commands that fail in script will fail the build
script:
  - npm test                # Run the tests

notifications:
  email: false
  slack: tud-contextproject-16:7oE95aUGOwGTYonAvcVxYcGr
